INSERT INTO users (u_id, u_username, u_password_hash, u_created_at) VALUES
  (1, 'lena', '$2b$10$LdtLCnADKY.0wzneDHyMjOO2GPOgV8Eie2fG85/Vz1EGIJ96bwvEe', '2026-04-28 10:00:00'),
  (2, 'max', '$2b$10$ejV9ka4Ef8MraIZcGYbAKusJmNYUvpg.C/6aPLwwSjZJ.QdybRxe.', '2026-04-28 10:05:00');

INSERT INTO categories (c_id, c_name) VALUES
  (1, 'Wohnen'),
  (2, 'Organisation'),
  (3, 'Garten'),
  (4, 'Textil'),
  (5, 'Kueche'),
  (6, 'Dekoration');

INSERT INTO difficulties (d_id, d_name) VALUES
  (1, 'leicht'),
  (2, 'mittel'),
  (3, 'schwer');

INSERT INTO materials (m_id, m_name) VALUES
  (1, 'Blechdose'),
  (2, 'Schraubglas'),
  (3, 'Holzkiste'),
  (4, 'altes T-Shirt'),
  (5, 'Glasflasche'),
  (6, 'Stoffrest'),
  (7, 'Versandkarton'),
  (8, 'Juteschnur'),
  (9, 'Holzleiste'),
  (10, 'Pappe'),
  (11, 'Kakteenerde'),
  (12, 'Sukkulente'),
  (13, 'Acrylfarbe'),
  (14, 'Schleifpapier'),
  (15, 'Holzoel'),
  (16, 'Baumwollband'),
  (17, 'Stabkerze'),
  (18, 'Packpapier'),
  (19, 'Klebeband'),
  (20, 'Filzgleiter'),
  (21, 'Kies'),
  (22, 'Stoffschere'),
  (23, 'Klebestift'),
  (24, 'Lineal'),
  (25, 'Konservendose'),
  (26, 'Tafelfarbe'),
  (27, 'Kreide'),
  (28, 'alte Jeans'),
  (29, 'Naehgarn'),
  (30, 'Reissverschluss'),
  (31, 'Holzbrett'),
  (32, 'Schrauben'),
  (33, 'Wandhaken'),
  (34, 'Gurkenglas'),
  (35, 'Essig'),
  (36, 'Natron'),
  (37, 'altes Geschirrtuch'),
  (38, 'Gummiband'),
  (39, 'Weinkiste'),
  (40, 'Rollen'),
  (41, 'Holzschrauben'),
  (42, 'Vorbohrer'),
  (43, 'Palettenbrett'),
  (44, 'Pflanzfolie'),
  (45, 'Blumenerde'),
  (46, 'Kraeutersamen'),
  (47, 'Korken'),
  (48, 'duenner Draht'),
  (49, 'Nadel'),
  (50, 'Glasreiniger'),
  (51, 'Sperrholzrest'),
  (52, 'Holzleim'),
  (53, 'Feinsaege'),
  (54, 'Klemmen');

INSERT INTO projects (
  p_id,
  p_u_id,
  p_c_id,
  p_d_id,
  p_title,
  p_slug,
  p_summary,
  p_description,
  p_estimated_minutes,
  p_image_url,
  p_created_at,
  p_updated_at
) VALUES
  (
    1,
    1,
    3,
    1,
    'Sukkulententopf aus Blechdose',
    'sukkulententopf-aus-blechdose',
    'Eine leere Blechdose wird zu einem kleinen Pflanzgefaess fuer robuste Sukkulenten.',
    'Blechdosen eignen sich gut fuer Sukkulenten, weil sie stabil sind und auch mit Gebrauchsspuren charmant aussehen. Wichtig sind geglaettete Kanten, etwas Drainage und eine Pflanze, die wenig Wasser braucht.',
    25,
    '/images/projects/kraeutertopf-konservendose.jpg',
    '2026-04-28 10:10:00',
    '2026-04-28 10:10:00'
  ),
  (
    2,
    1,
    2,
    1,
    'Stiftehalter aus Schraubglas',
    'stiftehalter-aus-schraubglas',
    'Ein leeres Glas wird zu einem ruhigen Stiftehalter fuer Schreibtisch oder Regal.',
    'Ein Schraubglas ist schwer genug, um Stifte sicher zu halten, und laesst sich ohne Spezialwerkzeug weiterverwenden. Mit einem Stoffrest, Schnur und kleinen Filzgleitern wirkt es sauber verarbeitet.',
    20,
    '/images/projects/stiftehalter-marmeladenglas.jpg',
    '2026-04-28 10:15:00',
    '2026-04-28 10:15:00'
  ),
  (
    3,
    1,
    1,
    2,
    'Regalbox aus Holzkiste',
    'regalbox-aus-holzkiste',
    'Eine gebrauchte Holzkiste wird zu einer offenen Regalbox fuer Buecher, Pflanzen oder kleine Alltagsdinge.',
    'Eine stabile Obst- oder Weinkiste kann nach dem Schleifen als einfache Regalbox weitergenutzt werden. Sie muss nicht neu aussehen; entscheidend sind saubere Kanten, ein sicherer Stand und eine Oberflaeche, die sich angenehm anfassen laesst.',
    65,
    '/images/projects/wandregal-holzkiste.jpg',
    '2026-04-28 10:20:00',
    '2026-04-28 10:20:00'
  ),
  (
    4,
    2,
    4,
    1,
    'Stoffbeutel aus altem T-Shirt',
    'stoffbeutel-aus-altem-t-shirt',
    'Aus einem aussortierten T-Shirt entsteht ein leichter Beutel ohne Naehmaschine.',
    'Ein T-Shirt mit festem Baumwollstoff laesst sich zu einem einfachen Beutel umarbeiten. Das Projekt ist besonders sinnvoll fuer Shirts, die nicht mehr getragen werden, aber noch keine Loecher im Bauch- oder Rueckenbereich haben.',
    25,
    '/images/projects/einkaufstasche-tshirt.jpg',
    '2026-04-28 10:25:00',
    '2026-04-28 10:25:00'
  ),
  (
    5,
    2,
    6,
    1,
    'Kerzenhalter aus Glasflasche',
    'kerzenhalter-aus-glasflasche',
    'Eine stabile Glasflasche wird zu einem schlichten Halter fuer eine passende Stabkerze.',
    'Schoene Glasflaschen muessen nicht sofort in den Glascontainer. Wenn der Flaschenhals zur Kerze passt und die Flasche kippsicher steht, entsteht daraus ein ruhiger Kerzenhalter fuer den Tisch.',
    15,
    '/images/projects/kerzenhalter-glasflasche.jpg',
    '2026-04-28 10:30:00',
    '2026-04-28 10:30:00'
  ),
  (
    6,
    2,
    2,
    2,
    'Dokumentenbox aus Versandkarton',
    'dokumentenbox-aus-versandkarton',
    'Stabiler Versandkarton wird zu einer Box fuer Hefte, Unterlagen oder lose Blaetter.',
    'Aus sauberem Versandkarton entsteht eine einfache Dokumentenbox, die im Regal oder auf dem Schreibtisch Ordnung schafft. Mit Packpapier und verstaerkten Kanten wirkt sie deutlich ruhiger als ein offener Karton.',
    45,
    '/images/projects/schreibtischbox-karton.jpg',
    '2026-04-28 10:35:00',
    '2026-04-28 10:35:00'
  ),
  (
    7,
    1,
    5,
    1,
    'Kraeuteretiketten aus Konservendosen',
    'kraeuteretiketten-aus-konservendosen',
    'Aus glatten Dosenstreifen entstehen wetterfeste kleine Schilder fuer Kraeutertoepfe.',
    'Duenne Konservendosen lassen sich mit etwas Vorsicht in beschreibbare Pflanzschilder verwandeln. Die Kanten muessen sorgfaeltig geglaettet werden, danach reicht Tafelfarbe fuer gut lesbare, wiederbeschreibbare Etiketten.',
    30,
    '/images/projects/kraeutertopf-konservendose.jpg',
    '2026-04-28 10:40:00',
    '2026-04-28 10:40:00'
  ),
  (
    8,
    1,
    4,
    2,
    'Federmappe aus alter Jeans',
    'federmappe-aus-alter-jeans',
    'Ein festes Jeansbein wird zu einer robusten Federmappe fuer Schule oder Werkbank.',
    'Abgetragene Jeans haben oft noch belastbaren Stoff an den Beinen. Mit einem geraden Zuschnitt, sauberen Naehten und einem wiederverwendeten Reissverschluss entsteht daraus eine Federmappe, die lange haelt.',
    70,
    '/images/projects/einkaufstasche-tshirt.jpg',
    '2026-04-28 10:45:00',
    '2026-04-28 10:45:00'
  ),
  (
    9,
    2,
    1,
    3,
    'Wandgarderobe aus Holzresten',
    'wandgarderobe-aus-holzresten',
    'Aus alten Brettern und einzelnen Haken entsteht eine stabile Garderobe fuer Flur oder Werkraum.',
    'Dieses Projekt braucht genaues Messen, Vorbohren und eine sichere Wandbefestigung. Unterschiedliche Holzreste duerfen sichtbar bleiben, solange die Rueckseite plan aufliegt und die Haken gleichmaessig belastet werden koennen.',
    120,
    '/images/projects/wandregal-holzkiste.jpg',
    '2026-04-28 10:50:00',
    '2026-04-28 10:50:00'
  ),
  (
    10,
    2,
    5,
    1,
    'Vorratsglas mit Stoffdeckel',
    'vorratsglas-mit-stoffdeckel',
    'Ein altes Gurkenglas wird gereinigt und mit Stoffdeckel als trockene Vorratsdose genutzt.',
    'Ein gut schliessendes Glas eignet sich fuer Nudeln, Reis oder selbst gemischtes Muesli. Der Stoffdeckel kaschiert Gebrauchsspuren am Schraubdeckel und macht das Glas im Kuechenregal einheitlicher.',
    25,
    '/images/projects/stiftehalter-marmeladenglas.jpg',
    '2026-04-28 10:55:00',
    '2026-04-28 10:55:00'
  ),
  (
    11,
    1,
    1,
    3,
    'Rollkiste aus alter Weinkiste',
    'rollkiste-aus-alter-weinkiste',
    'Eine stabile Weinkiste wird mit Bodenverstaerkung und Rollen zu einer mobilen Aufbewahrung.',
    'Fuer eine belastbare Rollkiste reicht es nicht, nur vier Rollen anzuschrauben. Die Kiste muss auf Risse geprueft, am Boden verstaerkt und sauber vorgebohrt werden, damit sie spaeter Decken, Werkzeug oder Spielzeug sicher traegt.',
    105,
    '/images/projects/wandregal-holzkiste.jpg',
    '2026-04-28 11:00:00',
    '2026-04-28 11:00:00'
  ),
  (
    12,
    2,
    3,
    3,
    'Vertikales Kraeuterregal aus Palettenbrett',
    'vertikales-kraeuterregal-aus-palettenbrett',
    'Ein Palettenbrett und alte Dosen werden zu einem kleinen haengenden Kraeutergarten.',
    'Das Kraeuterregal verbindet Holzarbeit mit Pflanzvorbereitung. Die Dosen brauchen Abflussloecher, das Brett muss geschliffen und wetterfest behandelt werden, und die Aufhaengung muss das Gewicht feuchter Erde tragen.',
    140,
    '/images/projects/kraeutertopf-konservendose.jpg',
    '2026-04-28 11:05:00',
    '2026-04-28 11:05:00'
  );

INSERT INTO project_materials (pm_p_id, pm_m_id, pm_amount, pm_unit, pm_note) VALUES
  (1, 1, '1', 'Stueck', 'sauber, trocken und ohne scharfe Innenkante'),
  (1, 11, '2', 'Handvoll', 'locker einfuellen, nicht fest pressen'),
  (1, 12, '2-3', 'Stueck', 'kleine Ableger oder flache Jungpflanzen'),
  (1, 21, '1', 'Handvoll', 'als Drainageschicht am Boden'),
  (1, 14, '1', 'Bogen', 'fuer Rand und kleine Roststellen'),
  (2, 2, '1', 'Stueck', 'Etikett vollstaendig entfernen'),
  (2, 6, '1', 'Streifen', 'breit genug fuer den unteren Glasbereich'),
  (2, 8, '40', 'cm', 'zum Fixieren des Stoffes'),
  (2, 20, '3-4', 'Stueck', 'unter den Glasboden kleben'),
  (3, 3, '1', 'Stueck', 'moeglichst trocken und nicht verzogen'),
  (3, 14, '2', 'Boegen', 'mittlere und feine Koernung'),
  (3, 15, 'etwas', NULL, 'sparsam auftragen und gut trocknen lassen'),
  (3, 9, '1', 'Stueck', 'nur noetig, wenn eine Kante verstaerkt werden muss'),
  (3, 20, '4', 'Stueck', 'fuer einen ruhigen Stand im Regal'),
  (4, 4, '1', 'Stueck', 'Baumwollshirt ohne duenne Loecher'),
  (4, 22, '1', 'Stueck', 'scharf genug fuer gerade Schnitte'),
  (4, 16, '60', 'cm', 'optional zur Verstaerkung der Traeger'),
  (5, 5, '1', 'Stueck', 'mit breitem, sicherem Stand'),
  (5, 17, '1', 'Stueck', 'muss fest im Flaschenhals sitzen'),
  (5, 8, '30', 'cm', 'optional fuer den Flaschenhals'),
  (6, 7, '1', 'Stueck', 'sauber und stabil, etwa Schuhkartonstaerke'),
  (6, 10, '1', 'Bogen', 'fuer Trennwaende und verstaerkte Kanten'),
  (6, 18, '1', 'Bogen', 'fuer eine ruhige Aussenflaeche'),
  (6, 19, '1', 'Rolle', 'zum Verstaerken der Innenecken'),
  (6, 23, '1', 'Stueck', 'fuer Packpapier und Kanten'),
  (6, 24, '1', 'Stueck', 'fuer gerade Falzlinien'),
  (7, 25, '1', 'Stueck', 'duenne Dose mit glatter Seitenwand'),
  (7, 14, '1', 'Bogen', 'zum Entschaerfen der Schnittkanten'),
  (7, 26, 'etwas', NULL, 'duenn auftragen'),
  (7, 27, '1', 'Stueck', 'zum spaeteren Beschriften'),
  (8, 28, '1', 'Bein', 'ohne duenne Stellen im Zuschnitt'),
  (8, 29, '1', 'Rolle', 'reissfestes Garn passend zum Stoff'),
  (8, 30, '1', 'Stueck', 'mindestens 18 cm lang'),
  (8, 24, '1', 'Stueck', 'fuer gerade Kanten'),
  (8, 22, '1', 'Stueck', 'fuer dicken Stoff geeignet'),
  (9, 31, '2-3', 'Stueck', 'trocken und mindestens 12 mm stark'),
  (9, 33, '4-5', 'Stueck', 'mit passender Tragkraft'),
  (9, 32, '12', 'Stueck', 'kurz genug, damit sie nicht durchstehen'),
  (9, 14, '2', 'Boegen', 'fuer Kanten und Oberflaeche'),
  (9, 15, 'etwas', NULL, 'als Oberflaechenschutz'),
  (9, 42, '1', 'Stueck', 'passend zu den Schrauben'),
  (10, 34, '1', 'Stueck', 'Deckel muss sauber schliessen'),
  (10, 35, '2', 'EL', 'zum Loesen von Geruch und Etikettenresten'),
  (10, 36, '1', 'TL', 'fuer die Grundreinigung'),
  (10, 6, '1', 'Stueck', 'etwas groesser als der Deckel'),
  (10, 38, '1', 'Stueck', 'kurz genug fuer festen Sitz'),
  (11, 39, '1', 'Stueck', 'ohne tiefe Risse im Boden'),
  (11, 31, '1', 'Stueck', 'als Bodenverstaerkung'),
  (11, 40, '4', 'Stueck', 'zwei davon mit Bremse, wenn vorhanden'),
  (11, 41, '16', 'Stueck', 'passend zur Rollenplatte'),
  (11, 42, '1', 'Stueck', 'zum Vorbohren'),
  (11, 14, '2', 'Boegen', 'fuer Splitter und Kanten'),
  (12, 43, '1', 'Stueck', 'trocken und ohne lose Splitter'),
  (12, 25, '3', 'Stueck', 'gleiche Groesse fuer ruhigen Sitz'),
  (12, 44, '3', 'Stueck', 'als Schutz zwischen Dose und Erde'),
  (12, 45, '3', 'Handvoll', 'locker und kraeutergeeignet'),
  (12, 46, '3', 'Sorten', 'z. B. Basilikum, Petersilie, Schnittlauch'),
  (12, 32, '6', 'Stueck', 'zur Befestigung der Dosen'),
  (12, 15, 'etwas', NULL, 'fuer das geschliffene Brett');

INSERT INTO project_steps (ps_p_id, ps_step_number, ps_text) VALUES
  (1, 1, 'Dose gruendlich auswaschen, vollstaendig trocknen lassen und die Innenkante mit Schleifpapier glaetten.'),
  (1, 2, 'Mit einem Nagel oder einer Ahle drei kleine Abflussloecher in den Boden setzen.'),
  (1, 3, 'Eine duenne Schicht Kies einfuellen, damit ueberschuessiges Wasser besser ablaufen kann.'),
  (1, 4, 'Kakteenerde locker einfuellen und die Sukkulenten so einsetzen, dass die Blaetter nicht am Dosenrand druecken.'),
  (1, 5, 'Erde leicht andruecken, die Dose aussen reinigen und erst nach einigen Tagen vorsichtig giessen.'),
  (2, 1, 'Glas mit warmem Wasser reinigen und Etikettenreste vollstaendig vom unteren Bereich loesen.'),
  (2, 2, 'Stoffstreifen einmal um das Glas legen, Laenge markieren und mit zwei Zentimetern Ueberlappung zuschneiden.'),
  (2, 3, 'Stoff straff anlegen und mit Juteschnur fixieren, damit keine losen Kanten abstehen.'),
  (2, 4, 'Filzgleiter unter den Glasboden kleben und kurz andruecken.'),
  (2, 5, 'Stifte nach Hoehe einsortieren und schwere Scheren oder Lineale eher nach hinten stellen.'),
  (3, 1, 'Holzkiste kontrollieren und lose Splitter, Klammern oder hervorstehende Naegel entfernen.'),
  (3, 2, 'Alle Griffoeffnungen und Aussenkanten zuerst mittel, dann fein abschleifen.'),
  (3, 3, 'Wackelige Stellen mit einer schmalen Holzleiste von innen verstaerken.'),
  (3, 4, 'Oberflaeche duenn mit Holzoel behandeln und ueberschuessiges Oel nach wenigen Minuten abwischen.'),
  (3, 5, 'Filzgleiter anbringen, die Kiste auf die Seite stellen und pruefen, ob sie ohne Wackeln steht.'),
  (3, 6, 'Leichte Gegenstaende einraeumen und das Gewicht gleichmaessig auf Boden und Seiten verteilen.'),
  (4, 1, 'T-Shirt flach ausbreiten, Falten glattziehen und den unteren Saum gerade ausrichten.'),
  (4, 2, 'Aermel entlang der Naht abschneiden und den Halsausschnitt zu einer groesseren Oeffnung erweitern.'),
  (4, 3, 'Unterkante in etwa zwei Zentimeter breite Streifen schneiden; dabei an beiden Seiten gleich tief einschneiden.'),
  (4, 4, 'Vorder- und Rueckseitenstreifen jeweils doppelt verknoten, bis der Boden geschlossen ist.'),
  (4, 5, 'Beutel wenden, an den Traegern leicht ziehen und schwache Stellen mit Baumwollband verstaerken.'),
  (5, 1, 'Flasche reinigen, Etiketten entfernen und pruefen, ob sie auf einer ebenen Flaeche sicher steht.'),
  (5, 2, 'Kerze testweise einsetzen; sie darf nicht wackeln und soll mindestens zwei Zentimeter tief im Hals sitzen.'),
  (5, 3, 'Flaschenhals bei Bedarf mit Juteschnur umwickeln, aber den Kerzensitz frei lassen.'),
  (5, 4, 'Kerze gerade einsetzen und den Halter auf eine hitzebestaendige Unterlage stellen.'),
  (5, 5, 'Vor dem Anzuenden Abstand zu Vorhaengen, Papier und Pflanzen kontrollieren.'),
  (6, 1, 'Karton auf eine passende Hoehe zuschneiden und die Vorderkante niedriger markieren, damit Unterlagen greifbar bleiben.'),
  (6, 2, 'Falzlinien mit Lineal vorziehen und die Seiten sauber nach innen knicken.'),
  (6, 3, 'Innenecken mit Klebeband verstaerken, damit die Box beim Befuellen ihre Form behaelt.'),
  (6, 4, 'Aus Pappe eine Trennwand zuschneiden, einsetzen und an Boden sowie Rueckwand fixieren.'),
  (6, 5, 'Aussenflaeche mit Packpapier beziehen und die Kanten mit Klebestift sauber umlegen.'),
  (6, 6, 'Box trocknen lassen, dann Hefte oder lose Blaetter nach Groesse sortiert einraeumen.'),
  (7, 1, 'Dose reinigen, Deckel und Boden entfernen und die Seitenwand vorsichtig zu einem flachen Blechstreifen oeffnen.'),
  (7, 2, 'Vier bis sechs schmale Schilder anzeichnen und mit der Stoffschere oder einer stabilen Schere ausschneiden.'),
  (7, 3, 'Alle Schnittkanten gruendlich mit Schleifpapier entschaerfen, bis sie nicht mehr kratzen.'),
  (7, 4, 'Eine Seite duenn mit Tafelfarbe streichen und vollstaendig trocknen lassen.'),
  (7, 5, 'Schilder mit Kreide beschriften und erst dann in die Erde stecken, wenn die Farbe trocken ist.'),
  (8, 1, 'Jeansbein auftrennen, Stoff glattlegen und zwei gleich grosse Rechtecke fuer Vorder- und Rueckseite zuschneiden.'),
  (8, 2, 'Reissverschluss rechts auf rechts an die langen Stoffkanten stecken und mit kleinen Stichen annaehnen.'),
  (8, 3, 'Stoffteile zusammenklappen, Seitenkanten ausrichten und die Ecken mit Klemmen fixieren.'),
  (8, 4, 'Seitennaehte langsam schliessen und die Enden des Reissverschlusses besonders fest vernaehen.'),
  (8, 5, 'Federmappe wenden, Ecken ausformen und pruefen, ob Stifte ohne Spannung hineinpassen.'),
  (9, 1, 'Bretter auf gleiche Laenge bringen und die spaetere Vorderseite nach Maserung und Macken sortieren.'),
  (9, 2, 'Rueckseite mit einer Holzleiste verbinden, Schraubpunkte markieren und alle Loecher vorbohren.'),
  (9, 3, 'Kanten und Flaechen schleifen, bis keine Splitter mehr abstehen.'),
  (9, 4, 'Hakenpositionen gleichmaessig anzeichnen und die Haken mit kurzen Schrauben befestigen.'),
  (9, 5, 'Holz duenn oelen, trocknen lassen und danach die Wandbefestigung passend zur Wand vorbereiten.'),
  (9, 6, 'Garderobe gerade ausrichten, fest montieren und mit einer leichten Jacke auf Belastung pruefen.'),
  (10, 1, 'Glas und Deckel mit heissem Wasser, Essig und Natron reinigen und danach gruendlich ausspuelen.'),
  (10, 2, 'Etikettenreste entfernen und das Glas vollstaendig trocknen lassen.'),
  (10, 3, 'Stoffrest kreisfoermig zuschneiden, sodass er rund zwei Zentimeter ueber den Deckelrand reicht.'),
  (10, 4, 'Deckel aufschrauben, Stoff darueberlegen und mit einem Gummiband straff unter dem Deckelrand fixieren.'),
  (10, 5, 'Glas mit trockenen Lebensmitteln fuellen und von aussen auf Dichtigkeit pruefen.'),
  (11, 1, 'Weinkiste leer pruefen, lose Naegel entfernen und rissige Stellen am Boden markieren.'),
  (11, 2, 'Sperrholz- oder Brettrest als Bodenverstaerkung zuschneiden und trocken einlegen.'),
  (11, 3, 'Verstaerkung vorbohren, mit Holzschrauben befestigen und ueberstehende Spitzen kontrollieren.'),
  (11, 4, 'Rollenpositionen an allen vier Ecken markieren und dabei Abstand zu den Kistenkanten lassen.'),
  (11, 5, 'Rollen vorbohren, anschrauben und jede Rolle einzeln auf festen Sitz pruefen.'),
  (11, 6, 'Kiste abschleifen, beladen und langsam rollen, um Wackeln oder schleifende Kanten zu finden.'),
  (12, 1, 'Palettenbrett auf Splitter, Naegel und Verzug pruefen und nur ein gerades Stueck verwenden.'),
  (12, 2, 'Brett schleifen, mit Holzoel schuetzen und vor der Montage trocknen lassen.'),
  (12, 3, 'Dosen reinigen, Bodenloecher setzen und innen mit Pflanzfolie auslegen.'),
  (12, 4, 'Dosenpositionen auf dem Brett markieren, vorbohren und die Dosen mit je zwei Schrauben befestigen.'),
  (12, 5, 'Erde einfuellen, Kraeutersamen setzen und die Oberflaeche leicht andruecken.'),
  (12, 6, 'Aufhaengung anbringen, Regal leer testweise einhaengen und erst danach vorsichtig angiessen.');
