INSERT INTO users (u_id, u_username, u_password_hash, u_created_at) VALUES
  (1, 'lena', '$2b$10$LdtLCnADKY.0wzneDHyMjOO2GPOgV8Eie2fG85/Vz1EGIJ96bwvEe', '2026-04-28 10:00:00'),
  (2, 'max', '$2b$10$ejV9ka4Ef8MraIZcGYbAKusJmNYUvpg.C/6aPLwwSjZJ.QdybRxe.', '2026-04-28 10:05:00');

INSERT INTO categories (c_id, c_name) VALUES
  (1, 'Wohnen'),
  (2, 'Organisation'),
  (3, 'Garten'),
  (4, 'Textil'),
  (5, 'Küche'),
  (6, 'Dekoration');

INSERT INTO difficulties (d_id, d_name) VALUES
  (1, 'leicht'),
  (2, 'mittel'),
  (3, 'schwer');

INSERT INTO materials (m_id, m_name) VALUES
  (1, 'Konservendose'),
  (2, 'Schraubglas'),
  (3, 'Holzkiste'),
  (4, 'altes T-Shirt'),
  (5, 'Glasflasche'),
  (6, 'Stoffrest'),
  (7, 'Versandkarton'),
  (8, 'Juteschnur'),
  (9, 'Holzleiste'),
  (10, 'Pappe'),
  (11, 'Kakteenerde'),
  (12, 'Kaktus'),
  (13, 'Acrylfarbe'),
  (14, 'Schleifpapier'),
  (15, 'Holzöl'),
  (16, 'Baumwollband'),
  (17, 'Stabkerze'),
  (18, 'Packpapier'),
  (19, 'Klebeband'),
  (20, 'Filzgleiter'),
  (21, 'Kies'),
  (22, 'Stoffschere'),
  (23, 'Klebestift'),
  (24, 'Lineal'),
  (25, 'Bettlaken'),
  (26, 'Nähgarn'),
  (27, 'Reißverschluss'),
  (28, 'Aktenmappe'),
  (29, 'Essig'),
  (30, 'Natron'),
  (31, 'Küchenetikett'),
  (32, 'Kreidestift'),
  (33, 'LED-Lichterkette'),
  (34, 'dünner Draht'),
  (35, 'Seitenschneider'),
  (36, 'Palettenbrett'),
  (37, 'Schrauben'),
  (38, 'Rollen'),
  (39, 'Vorbohrer'),
  (40, 'Winkelverbinder'),
  (41, 'alte Leiter'),
  (42, 'Holzbrett'),
  (43, 'Wandhalterung'),
  (44, 'Dübel'),
  (45, 'alter Koffer'),
  (46, 'Tischbein'),
  (47, 'Sperrholzplatte'),
  (48, 'Unterlegscheibe'),
  (49, 'Holzleim'),
  (50, 'Feinsäge');

INSERT INTO projects (
  p_id,
  p_u_id,
  p_c_id,
  p_d_id,
  p_title,
  p_slug,
  p_summary,
  p_description,
  p_estimated_minutes,
  p_image_url,
  p_created_at,
  p_updated_at
) VALUES
  (
    1,
    1,
    3,
    1,
    'Kräutertopf aus Konservendose',
    'kraeutertopf-aus-konservendose',
    'Eine saubere Konservendose wird zu einem kleinen Pflanztopf für Fensterbankkräuter oder Kakteen.',
    'Die Dose auf dem Bild funktioniert gut als kleines Pflanzgefäß, weil sie stabil steht und wenig Platz braucht. Mit geglätteter Kante, Drainage und passender Erde entsteht daraus ein einfacher Topf für robuste Pflanzen.',
    25,
    '/images/projects/tin-can-cactus-planter.jpg',
    '2026-04-28 10:10:00',
    '2026-04-28 10:10:00'
  ),
  (
    2,
    1,
    2,
    1,
    'Stiftehalter aus Schraubglas',
    'stiftehalter-aus-schraubglas',
    'Ein leeres Schraubglas wird zu einem stabilen Halter für Buntstifte, Pinsel oder Scheren.',
    'Das Glas zeigt klar, wie gut sich alte Schraubgläser für Ordnung am Arbeitsplatz eignen. Es ist schwer genug, kippt nicht sofort um und lässt den Inhalt sichtbar bleiben.',
    20,
    '/images/projects/jar-pencil-holder.jpg',
    '2026-04-28 10:15:00',
    '2026-04-28 10:15:00'
  ),
  (
    3,
    2,
    1,
    2,
    'Regalbox aus Holzkiste',
    'regalbox-aus-holzkiste',
    'Eine stabile Holzkiste wird geschliffen und als offene Regalbox an der Wand oder auf einem Regal genutzt.',
    'Die sichtbare Holzkiste wirkt als dekorative Aufbewahrung, ohne ihren gebrauchten Charakter zu verlieren. Wichtig sind saubere Kanten, eine belastbare Rückseite und ein sicherer Stand.',
    60,
    '/images/projects/wooden-crate-shelf.jpg',
    '2026-04-28 10:20:00',
    '2026-04-28 10:20:00'
  ),
  (
    4,
    2,
    4,
    2,
    'Stoffbeutel aus altem Bettlaken',
    'stoffbeutel-aus-altem-bettlaken',
    'Aus festem Baumwollstoff entsteht ein schlichter Beutel für Bücher, Einkäufe oder Schulsachen.',
    'Der helle Beutel auf dem Bild passt zu alten Bettlaken oder Vorhangstoffen, die noch stabil sind. Mit geraden Nähten und verstärkten Trägern wird daraus ein alltagstauglicher Stoffbeutel.',
    65,
    '/images/projects/fabric-tote-bag.jpg',
    '2026-04-28 10:25:00',
    '2026-04-28 10:25:00'
  ),
  (
    5,
    1,
    6,
    1,
    'Kerzenhalter aus Glasflasche',
    'kerzenhalter-aus-glasflasche',
    'Eine leere Glasflasche wird mit einer passenden Stabkerze zu einem einfachen Tischlicht.',
    'Die Flasche auf dem Bild zeigt die wichtigste Voraussetzung: ein sicherer Stand und ein Flaschenhals, in dem die Kerze fest sitzt. So entsteht ohne viel Werkzeug eine ruhige Tischdekoration.',
    15,
    '/images/projects/wine-bottle-candle-holder.jpg',
    '2026-04-28 10:30:00',
    '2026-04-28 10:30:00'
  ),
  (
    6,
    2,
    2,
    2,
    'Archivbox aus Versandkarton',
    'archivbox-aus-versandkarton',
    'Ein fester Versandkarton wird zu einer beschrifteten Box für Mappen, Hefte und lose Unterlagen.',
    'Die Kartonbox mit Aktenmappen macht die spätere Nutzung sofort verständlich. Mit verstärktem Boden, Trennstegen und einer niedrigen Vorderkante wird daraus eine praktische Ablage für den Schreibtisch.',
    50,
    '/images/projects/cardboard-file-box.jpg',
    '2026-04-28 10:35:00',
    '2026-04-28 10:35:00'
  ),
  (
    7,
    1,
    5,
    1,
    'Vorratsgläser für die Küche',
    'vorratsglaeser-fuer-die-kueche',
    'Mehrere saubere Schraubgläser werden zu übersichtlichen Vorratsgläsern für trockene Lebensmittel.',
    'Die Gläser auf dem Bild zeigen, wie ruhig eine Küche wirken kann, wenn Reis, Kerne oder Gewürze sichtbar und beschriftet gelagert werden. Alte Gläser brauchen dafür nur eine gründliche Reinigung und klare Etiketten.',
    30,
    '/images/projects/jar-pantry-storage.jpg',
    '2026-04-28 10:40:00',
    '2026-04-28 10:40:00'
  ),
  (
    8,
    2,
    6,
    2,
    'Hängelaterne aus Schraubglas',
    'haengelaterne-aus-schraubglas',
    'Ein Schraubglas wird mit Drahtgriff und LED-Lichterkette zu einer kleinen Laterne für Balkon oder Zimmer.',
    'Das hängende Glas mit Licht zeigt eine einfache, aber wirkungsvolle Deko-Idee. Für den Alltag ist eine LED-Lichterkette sinnvoller als eine offene Flamme, weil das Glas hängen kann und nicht heiß wird.',
    55,
    '/images/projects/jar-lantern.jpg',
    '2026-04-28 10:45:00',
    '2026-04-28 10:45:00'
  ),
  (
    9,
    1,
    1,
    3,
    'Couchtisch aus Palettenholz',
    'couchtisch-aus-palettenholz',
    'Aus Palettenbrettern entsteht ein niedriger Couchtisch mit geschliffener Oberfläche und stabiler Unterkonstruktion.',
    'Der helle Tisch auf dem Bild ist schlicht, aber das Projekt braucht genaues Arbeiten: Bretter müssen sortiert, verschraubt, geschliffen und gegen Splitter geschützt werden. Erst dann eignet sich die Fläche für Bücher, Pflanzen oder Getränke.',
    130,
    '/images/projects/pallet-coffee-table.jpg',
    '2026-04-28 10:50:00',
    '2026-04-28 10:50:00'
  ),
  (
    10,
    2,
    1,
    3,
    'Bücherregal aus alter Leiter',
    'buecherregal-aus-alter-leiter',
    'Eine alte Holzleiter wird gereinigt, gesichert und als schmales Bücherregal genutzt.',
    'Die Leiter vor den Bücherreihen zeigt, warum dieses Projekt nur mit stabiler Befestigung sinnvoll ist. Die Leiter muss tragfähig sein, darf nicht wackeln und braucht feste Auflagepunkte für Bücher oder kleine Bretter.',
    120,
    '/images/projects/ladder-bookshelf.jpg',
    '2026-04-28 10:55:00',
    '2026-04-28 10:55:00'
  ),
  (
    11,
    1,
    1,
    3,
    'Beistelltisch aus altem Koffer',
    'beistelltisch-aus-altem-koffer',
    'Ein alter Koffer wird verstärkt und mit Beinen zu einem kleinen Tisch für Tasse, Vase oder Bücher.',
    'Der Koffer auf dem Bild funktioniert als Blickfang, aber für einen belastbaren Tisch braucht er eine feste Innenplatte. Die Beine müssen sauber verschraubt werden, damit der Koffer nicht nachgibt oder kippt.',
    100,
    '/images/projects/suitcase-side-table.jpg',
    '2026-04-28 11:00:00',
    '2026-04-28 11:00:00'
  );

INSERT INTO project_materials (pm_p_id, pm_m_id, pm_amount, pm_unit, pm_note) VALUES
  (1, 1, '1', 'Stück', 'sauber, trocken und ohne scharfe Innenkante'),
  (1, 11, '2', 'Handvoll', 'locker einfüllen'),
  (1, 12, '1', 'Stück', 'kleiner Kaktus oder robuste Jungpflanze'),
  (1, 21, '1', 'Handvoll', 'als Drainageschicht'),
  (1, 14, '1', 'Bogen', 'für Rand und kleine Roststellen'),
  (2, 2, '1', 'Stück', 'Etikett vollständig entfernen'),
  (2, 6, '1', 'Streifen', 'optional für den unteren Glasrand'),
  (2, 8, '40', 'cm', 'zum Fixieren des Stoffstreifens'),
  (2, 20, '3-4', 'Stück', 'unter den Glasboden kleben'),
  (3, 3, '1', 'Stück', 'trocken und nicht verzogen'),
  (3, 14, '2', 'Bögen', 'mittlere und feine Körnung'),
  (3, 15, 'etwas', NULL, 'dünn auftragen und gut trocknen lassen'),
  (3, 9, '1', 'Stück', 'für eine schwache Kante oder Rückseite'),
  (3, 37, '6-8', 'Stück', 'kurz genug, damit sie nicht durchstehen'),
  (4, 25, '1', 'Stück', 'fester Baumwollstoff ohne dünne Stellen'),
  (4, 22, '1', 'Stück', 'scharf genug für gerade Schnitte'),
  (4, 26, '1', 'Rolle', 'reißfestes Garn'),
  (4, 16, '80', 'cm', 'für die Träger'),
  (5, 5, '1', 'Stück', 'mit breitem, sicherem Stand'),
  (5, 17, '1', 'Stück', 'muss fest im Flaschenhals sitzen'),
  (5, 8, '30', 'cm', 'optional für den Flaschenhals'),
  (6, 7, '1', 'Stück', 'sauber und stabil'),
  (6, 10, '1', 'Bogen', 'für Trennstege und verstärkte Kanten'),
  (6, 28, '4-6', 'Stück', 'als Einteilung für Unterlagen'),
  (6, 19, '1', 'Rolle', 'zum Verstärken der Innenecken'),
  (6, 24, '1', 'Stück', 'für gerade Falzlinien'),
  (7, 2, '4-6', 'Stück', 'gleich groß oder nach Inhalt sortiert'),
  (7, 29, '2', 'EL', 'zum Lösen von Geruch und Etikettenresten'),
  (7, 30, '1', 'TL', 'für die Grundreinigung'),
  (7, 31, '4-6', 'Stück', 'gut lesbar beschriften'),
  (7, 32, '1', 'Stück', 'für Deckel oder Etiketten'),
  (8, 2, '1', 'Stück', 'mit intaktem Rand'),
  (8, 33, '1', 'Stück', 'batteriebetrieben, keine offene Flamme'),
  (8, 34, '60', 'cm', 'für Griff und Aufhängung'),
  (8, 35, '1', 'Stück', 'zum Kürzen und Biegen des Drahts'),
  (8, 8, '30', 'cm', 'zum Umwickeln des Glasrands'),
  (9, 36, '4-6', 'Stück', 'trocken und möglichst gerade'),
  (9, 37, '20', 'Stück', 'passend zur Brettstärke'),
  (9, 38, '4', 'Stück', 'optional, wenn der Tisch beweglich sein soll'),
  (9, 39, '1', 'Stück', 'gegen gespaltenes Holz'),
  (9, 40, '4', 'Stück', 'für eine stabile Unterkonstruktion'),
  (9, 14, '3', 'Bögen', 'grob, mittel und fein'),
  (9, 15, 'etwas', NULL, 'als Schutz für die Oberfläche'),
  (10, 41, '1', 'Stück', 'stabil und ohne morsche Sprossen'),
  (10, 42, '2-3', 'Stück', 'als zusätzliche Ablagen'),
  (10, 43, '2', 'Stück', 'für sichere Wandbefestigung'),
  (10, 44, '2-4', 'Stück', 'passend zur Wand'),
  (10, 14, '2', 'Bögen', 'für Splitter und alte Lackkanten'),
  (11, 45, '1', 'Stück', 'Schloss und Scharniere prüfen'),
  (11, 46, '4', 'Stück', 'gleich lang und stabil'),
  (11, 47, '1', 'Stück', 'als Innenverstärkung'),
  (11, 37, '16', 'Stück', 'passend zu Tischbeinen und Innenplatte'),
  (11, 48, '16', 'Stück', 'verteilen den Druck im Kofferboden'),
  (11, 39, '1', 'Stück', 'zum Vorbohren');

INSERT INTO project_steps (ps_p_id, ps_step_number, ps_text) VALUES
  (1, 1, 'Dose gründlich auswaschen, trocknen lassen und die Innenkante mit Schleifpapier glätten.'),
  (1, 2, 'Drei kleine Abflusslöcher in den Boden setzen, damit sich kein Wasser staut.'),
  (1, 3, 'Eine dünne Schicht Kies einfüllen und darüber Kakteenerde locker verteilen.'),
  (1, 4, 'Kaktus vorsichtig einsetzen, Erde rundherum auffüllen und leicht andrücken.'),
  (1, 5, 'Dose außen reinigen und erst nach einigen Tagen sparsam gießen.'),
  (2, 1, 'Schraubglas mit warmem Wasser reinigen und Etikettenreste vollständig lösen.'),
  (2, 2, 'Stoffstreifen zuschneiden und straff um den unteren Glasbereich legen.'),
  (2, 3, 'Stoff mit Juteschnur fixieren und lose Enden kurz abschneiden.'),
  (2, 4, 'Filzgleiter unter den Glasboden kleben, damit der Tisch nicht verkratzt.'),
  (2, 5, 'Stifte nach Höhe einsortieren und schwere Scheren eher nach hinten stellen.'),
  (3, 1, 'Holzkiste kontrollieren und lose Splitter, Klammern oder Nägel entfernen.'),
  (3, 2, 'Außenkanten, Grifföffnungen und sichtbare Flächen zuerst mittel, dann fein schleifen.'),
  (3, 3, 'Schwache Stellen von innen mit einer Holzleiste verstärken.'),
  (3, 4, 'Oberfläche dünn mit Holzöl behandeln und überschüssiges Öl abwischen.'),
  (3, 5, 'Kiste aufstellen oder sicher an der Wand befestigen und erst danach beladen.'),
  (4, 1, 'Bettlaken glatt ausbreiten und zwei gleich große Rechtecke zuschneiden.'),
  (4, 2, 'Obere Kanten zweimal nach innen falten und sauber absteppen.'),
  (4, 3, 'Seitennähte und Bodennaht schließen, dabei die Ecken langsam führen.'),
  (4, 4, 'Baumwollband als Träger zuschneiden und mit mehreren Nähten befestigen.'),
  (4, 5, 'Beutel wenden, Nähte prüfen und mit Büchern vorsichtig auf Belastung testen.'),
  (5, 1, 'Flasche reinigen, Etiketten entfernen und auf einer ebenen Fläche auf Standfestigkeit prüfen.'),
  (5, 2, 'Kerze testweise einsetzen; sie soll gerade und mindestens zwei Zentimeter tief sitzen.'),
  (5, 3, 'Flaschenhals bei Bedarf mit Juteschnur dekorieren, ohne den Kerzensitz zu blockieren.'),
  (5, 4, 'Kerze gerade einsetzen und den Halter auf eine hitzebeständige Unterlage stellen.'),
  (5, 5, 'Vor dem Anzünden Abstand zu Papier, Vorhängen und Pflanzen kontrollieren.'),
  (6, 1, 'Karton auf passende Höhe kürzen und die Vorderkante niedriger markieren.'),
  (6, 2, 'Boden und Ecken mit Klebeband verstärken, damit die Box beim Füllen stabil bleibt.'),
  (6, 3, 'Aus Pappe Trennstege zuschneiden und mit Klebeband oder Klebestift fixieren.'),
  (6, 4, 'Außenfläche mit Packpapier beziehen und Kanten sauber umlegen.'),
  (6, 5, 'Aktenmappen einsetzen, Fächer beschriften und die Box nach Gewicht sortiert befüllen.'),
  (7, 1, 'Schraubgläser und Deckel mit heißem Wasser, Essig und Natron reinigen.'),
  (7, 2, 'Gläser vollständig trocknen lassen, damit trockene Lebensmittel nicht verklumpen.'),
  (7, 3, 'Deckel oder Vorderseite mit Küchenetiketten bekleben.'),
  (7, 4, 'Inhalt mit Kreidestift gut lesbar notieren und bei Bedarf ein Datum ergänzen.'),
  (7, 5, 'Gläser nach Höhe und Nutzung im Regal anordnen, schwere Gläser nach unten stellen.'),
  (8, 1, 'Schraubglas reinigen und prüfen, ob der Rand frei von Sprüngen ist.'),
  (8, 2, 'Draht zweimal unter dem Glasrand herumführen und links sowie rechts kleine Ösen biegen.'),
  (8, 3, 'Einen Drahtbügel als Griff einsetzen und mit dem Seitenschneider sauber schließen.'),
  (8, 4, 'LED-Lichterkette locker ins Glas legen, damit Batteriebox und Schalter erreichbar bleiben.'),
  (8, 5, 'Glas am Griff testen und erst dann an einem Haken oder Ast aufhängen.'),
  (9, 1, 'Palettenbretter sortieren und nur gerade, trockene Bretter ohne tiefe Risse verwenden.'),
  (9, 2, 'Bretter auf Länge schneiden, vorbohren und zu einer ebenen Tischplatte verschrauben.'),
  (9, 3, 'Unterseite mit Winkelverbindern oder Querleisten stabilisieren.'),
  (9, 4, 'Kanten und Fläche gründlich schleifen, bis keine Splitter mehr stehen bleiben.'),
  (9, 5, 'Rollen oder Füße montieren und den Tisch auf geradem Boden auf Wackeln prüfen.'),
  (9, 6, 'Holz dünn ölen, trocknen lassen und die Oberfläche vor der ersten Nutzung abwischen.'),
  (10, 1, 'Leiter auf Risse, lockere Sprossen und alte Nägel prüfen.'),
  (10, 2, 'Alle rauen Stellen schleifen und lose Farbreste vorsichtig entfernen.'),
  (10, 3, 'Zusätzliche Bretter als Ablagen zuschneiden und auf passenden Sprossen befestigen.'),
  (10, 4, 'Wandhalterungen markieren, Dübel setzen und die Leiter gegen Kippen sichern.'),
  (10, 5, 'Bücher von unten nach oben einräumen und das Gewicht gleichmäßig verteilen.'),
  (11, 1, 'Koffer öffnen, Scharniere prüfen und den Boden von innen ausmessen.'),
  (11, 2, 'Sperrholzplatte zuschneiden und flach in den Kofferboden legen.'),
  (11, 3, 'Positionen der Tischbeine markieren und durch Kofferboden sowie Innenplatte vorbohren.'),
  (11, 4, 'Tischbeine mit Schrauben und Unterlegscheiben befestigen, ohne den Kofferboden einzudrücken.'),
  (11, 5, 'Koffer schließen, Tisch aufstellen und alle Beine nachziehen.'),
  (11, 6, 'Mit einer leichten Last testen und erst danach Tasse, Vase oder Bücher daraufstellen.');
