INSERT INTO users (u_id, u_username, u_password_hash, u_created_at) VALUES
  (1, 'upcyclehub', 'seed-password-hash', '2026-04-28 10:00:00');

INSERT INTO categories (c_id, c_name) VALUES
  (1, 'Wohnen'),
  (2, 'Organisation'),
  (3, 'Garten'),
  (4, 'Textil');

INSERT INTO difficulties (d_id, d_name) VALUES
  (1, 'leicht'),
  (2, 'mittel'),
  (3, 'anspruchsvoll');

INSERT INTO materials (m_id, m_name) VALUES
  (1, 'Konservendose'),
  (2, 'Marmeladenglas'),
  (3, 'Holzkiste'),
  (4, 'altes T-Shirt'),
  (5, 'Glasflasche'),
  (6, 'Stoffrest'),
  (7, 'stabiler Karton'),
  (8, 'Juteschnur'),
  (9, 'Holzleiste'),
  (10, 'Pappe'),
  (11, 'Pflanzenerde'),
  (12, 'Kräuterpflanze'),
  (13, 'Acrylfarbe'),
  (14, 'Schrauben'),
  (15, 'Wandhaken'),
  (16, 'Baumwollband'),
  (17, 'Kerze'),
  (18, 'Packpapier'),
  (19, 'Klebeband'),
  (20, 'Filzgleiter');

INSERT INTO projects (
  p_id,
  p_u_id,
  p_c_id,
  p_d_id,
  p_title,
  p_slug,
  p_summary,
  p_description,
  p_estimated_minutes,
  p_image_url,
  p_created_at,
  p_updated_at
) VALUES
  (
    1,
    1,
    3,
    1,
    'Kräutertopf aus Konservendose',
    'kraeutertopf-aus-konservendose',
    'Eine ausgespülte Konservendose wird zu einem stabilen Topf für Küchenkräuter.',
    'Leere Konservendosen eignen sich gut als kleine Pflanzgefäße, wenn die Kanten sauber geglättet und Abflusslöcher ergänzt werden. Mit etwas Schnur oder Farbe passt der Topf auf die Fensterbank, ohne wie Verpackungsmüll zu wirken.',
    45,
    '/images/projects/kraeutertopf-konservendose.jpg',
    '2026-04-28 10:10:00',
    '2026-04-28 10:10:00'
  ),
  (
    2,
    1,
    2,
    1,
    'Stiftehalter aus Marmeladenglas',
    'stiftehalter-aus-marmeladenglas',
    'Ein leeres Schraubglas wird zu einem ruhigen Stiftehalter für den Schreibtisch.',
    'Marmeladengläser sind schwer genug, um Stifte sicher zu halten, und lassen sich ohne Spezialwerkzeug weiterverwenden. Stoffreste oder Juteschnur geben dem Glas mehr Griff und verdecken kleine Klebereste vom Etikett.',
    25,
    '/images/projects/stiftehalter-marmeladenglas.jpg',
    '2026-04-28 10:15:00',
    '2026-04-28 10:15:00'
  ),
  (
    3,
    1,
    1,
    2,
    'Wandregal aus Holzkiste',
    'wandregal-aus-holzkiste',
    'Eine alte Holzkiste wird zu einem kleinen Wandregal für Bücher, Pflanzen oder Tassen.',
    'Eine gebrauchte Holzkiste kann nach dem Reinigen und Abschleifen als offenes Regal weiterleben. Besonders gut funktioniert das Projekt mit stabilen Obst- oder Weinkisten, die eine gerade Rückseite haben.',
    90,
    '/images/projects/wandregal-holzkiste.jpg',
    '2026-04-28 10:20:00',
    '2026-04-28 10:20:00'
  ),
  (
    4,
    1,
    4,
    2,
    'Einkaufstasche aus T-Shirt',
    'einkaufstasche-aus-t-shirt',
    'Aus einem aussortierten T-Shirt entsteht eine einfache Tasche ohne Nähmaschine.',
    'Ein altes T-Shirt kann mit wenigen Schnitten in eine wiederverwendbare Einkaufstasche verwandelt werden. Der elastische Stoff eignet sich vor allem für leichte Einkäufe wie Obst, Brot oder Drogerieartikel.',
    40,
    '/images/projects/einkaufstasche-tshirt.jpg',
    '2026-04-28 10:25:00',
    '2026-04-28 10:25:00'
  ),
  (
    5,
    1,
    1,
    1,
    'Kerzenhalter aus Glasflasche',
    'kerzenhalter-aus-glasflasche',
    'Eine stabile Glasflasche wird zu einem schlichten Halter für eine passende Kerze.',
    'Schöne Glasflaschen müssen nicht sofort in den Glascontainer. Wenn der Flaschenhals zur Kerze passt und die Flasche sicher steht, entsteht daraus ein einfacher Kerzenhalter für den Tisch.',
    20,
    '/images/projects/kerzenhalter-glasflasche.jpg',
    '2026-04-28 10:30:00',
    '2026-04-28 10:30:00'
  ),
  (
    6,
    1,
    2,
    2,
    'Schreibtischbox aus Karton',
    'schreibtischbox-aus-karton',
    'Stabiler Versandkarton wird zu einer Box für Notizen, Kabel und kleine Schreibwaren.',
    'Aus sauberem Karton und Pappe entsteht eine einfache Ordnungshilfe für den Arbeitsplatz. Das Projekt ist praktisch, weil Größe und Fächer direkt an den eigenen Schreibtisch angepasst werden können.',
    60,
    '/images/projects/schreibtischbox-karton.jpg',
    '2026-04-28 10:35:00',
    '2026-04-28 10:35:00'
  );

INSERT INTO project_materials (pm_p_id, pm_m_id) VALUES
  (1, 1),
  (1, 8),
  (1, 11),
  (1, 12),
  (1, 13),
  (2, 2),
  (2, 6),
  (2, 8),
  (2, 20),
  (3, 3),
  (3, 9),
  (3, 14),
  (3, 15),
  (4, 4),
  (4, 16),
  (5, 5),
  (5, 8),
  (5, 17),
  (6, 7),
  (6, 10),
  (6, 18),
  (6, 19);

INSERT INTO project_steps (ps_p_id, ps_step_number, ps_text) VALUES
  (1, 1, 'Dose gründlich auswaschen, Etikett entfernen und scharfe Kanten mit Schleifpapier glätten.'),
  (1, 2, 'Drei bis vier kleine Abflusslöcher in den Boden setzen, damit sich später kein Wasser staut.'),
  (1, 3, 'Außenseite trocknen lassen und mit Acrylfarbe oder Juteschnur schlicht gestalten.'),
  (1, 4, 'Eine dünne Schicht grobe Erde einfüllen, dann Pflanzenerde ergänzen.'),
  (1, 5, 'Kräuterpflanze einsetzen, Erde leicht andrücken und vorsichtig angießen.'),
  (2, 1, 'Glas und Deckelrand mit warmem Wasser reinigen, bis keine Klebereste mehr spürbar sind.'),
  (2, 2, 'Stoffrest passend zuschneiden und um den unteren Glasbereich legen.'),
  (2, 3, 'Stoff mit Juteschnur fixieren und die Enden sauber verknoten.'),
  (2, 4, 'Filzgleiter unter das Glas kleben, damit der Tisch nicht verkratzt.'),
  (2, 5, 'Stifte nach Höhe sortieren und das Glas nicht zu voll beladen.'),
  (3, 1, 'Holzkiste prüfen und lose Splitter oder Nägel entfernen.'),
  (3, 2, 'Oberfläche abschleifen, besonders an Grifföffnungen und Kanten.'),
  (3, 3, 'Bei Bedarf eine Holzleiste als zusätzliche Ablage im Inneren anschrauben.'),
  (3, 4, 'Position an der Wand markieren und passende Wandhaken oder Schrauben vorbereiten.'),
  (3, 5, 'Kiste waagrecht befestigen und an mehreren Punkten auf festen Sitz prüfen.'),
  (3, 6, 'Nur leichte Gegenstände einräumen und das Gewicht gleichmäßig verteilen.'),
  (4, 1, 'T-Shirt flach hinlegen und den unteren Saum glatt ausrichten.'),
  (4, 2, 'Ärmel abschneiden und den Halsausschnitt zu einer größeren Öffnung erweitern.'),
  (4, 3, 'Unterkante in gleich breite Streifen schneiden, ohne die Seitennaht zu beschädigen.'),
  (4, 4, 'Jeweils Vorder- und Rückseitenstreifen doppelt verknoten, bis der Boden geschlossen ist.'),
  (4, 5, 'Tasche wenden, Knoten kontrollieren und bei Bedarf mit Baumwollband verstärken.'),
  (5, 1, 'Flasche gründlich reinigen und vollständig trocknen lassen.'),
  (5, 2, 'Standfläche prüfen; wackelige Flaschen nicht für Kerzen verwenden.'),
  (5, 3, 'Flaschenhals mit Juteschnur umwickeln, wenn kleine Kratzer verdeckt werden sollen.'),
  (5, 4, 'Kerze vorsichtig einsetzen und nur verwenden, wenn sie fest im Hals sitzt.'),
  (5, 5, 'Kerzenhalter auf eine hitzebeständige Unterlage stellen und nie unbeaufsichtigt brennen lassen.'),
  (6, 1, 'Karton auf die gewünschte Grundfläche zuschneiden und Falzkanten mit Lineal vorziehen.'),
  (6, 2, 'Seitenteile aufstellen und die Ecken von innen mit Klebeband stabilisieren.'),
  (6, 3, 'Aus Pappe ein oder zwei Trennwände zuschneiden und passend einsetzen.'),
  (6, 4, 'Außenflächen mit Packpapier beziehen, damit die Box ruhiger wirkt.'),
  (6, 5, 'Klebestellen trocknen lassen und anschließend Notizen, Kabel oder Zubehör einsortieren.');
